on:
  push:
    branches: [ main ]
  release:
    types:
      - created
jobs:
  build-docker:
    uses: Thiritin/workflows/.github/workflows/docker-semver.yml@main
    secrets:
      DockerHubUser: ${{ secrets.DOCKERHUB_USERNAME }}
      DockerHubPass: ${{ secrets.DOCKERHUB_PASSWORD }}
      DockerHubPrefix: eurofurence
