name: Docker Build and Publish
on:
  push:
    branches:
      - 'main'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-**'

  release:
    types:
      - published

jobs:
  build-and-push-image:
    uses: eurofurence/workflows/.github/workflows/docker-buildx-push.yml@main

    permissions:
      contents: read
      packages: write

    with:
      image-name: ${{ github.repository }}
      dockerfile: ./Dockerfile
      # build-context: .
      # build-args: '--build-arg FOO=bar'

    secrets:
      ghcr-token: ${{ secrets.GITHUB_TOKEN }}
